# /// script
# requires-python = ">=3.13"
# dependencies = [
#     "pyyaml==6.0.2",
# ]
# ///

import pathlib

import yaml

gh_dir = pathlib.Path(__file__).parent
workflow_dir = gh_dir / "workflows"
workflow_file = workflow_dir / "auto_update.yml"

indexers_dir = gh_dir.parent / "indexers"


def iter_indexer_files():
    for file in indexers_dir.glob("*.py"):
        if not file.name.startswith("_"):
            yield file


def build_tree():
    files = [p.name.removesuffix(".py") for p in iter_indexer_files()]
    return {
        "name": "Auto Update",
        "on": {
            "workflow_dispatch": {
                "inputs": {
                    "indexer": {
                        "description": "the indexer to run",
                        "required": False,
                        "default": "",
                        "type": "choice",
                        "options": ["", *sorted(files)],
                    }
                }
            },
            "schedule": [{"cron": "23 23 * * *"}],
        },
        "jobs": {
            "update": {
                "runs-on": "ubuntu-latest",
                "steps": [
                    {"uses": "actions/checkout@v4"},
                    {"name": "Print Option", "run": "echo ${{ inputs.indexer }}"},
                    *[
                        {
                            "name": f"index {file}",
                            "if": f"${{{{ inputs.indexer == '' || inputs.indexer == '{file}' }}}}",
                            "uses": "cibere/Rtfm-Indexes@run-indexer-action",
                            "with": {
                                "filename": file,
                                "error_hook": "${{ secrets.INDEX_ERROR_HOOK_URL }}",
                            },
                        }
                        for file in files
                    ],
                    {
                        "name": "Push Changes",
                        "continue-on-error": True,
                        "run": "\n".join(
                            [
                                "git add indexes_v2",
                                "git stash",
                                "git fetch",
                                "git switch indexes-v2",
                                "git checkout stash -- indexes_v2",
                                "git add indexes_v2",
                                'git -c user.name="github-actions[bot]" -c user.email="41898282+github-actions[bot]@users.noreply.github.com" commit --author="cibere <71997063+cibere@users.noreply.github.com>" -m "Auto Update Indexes"',
                                "git push --force",
                            ]
                        ),
                    },
                ],
            }
        },
    }


def main():
    header = "# this is automatically generated by\n# https://github.com/cibere/Rtfm-Indexes/blob/master/.github/update_workflow_builder.py\n\n"
    workflow_file.write_text(header + yaml.dump(build_tree()))


if __name__ == "__main__":
    main()
