name: 'Run Parser'
description: ''
inputs:
  filename:
    required: true
  error_hook:
    required: true

runs:
  using: "composite"
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v5

    - name: Run Parser
      continue-on-error: true
      id: parser
      shell: bash
      run: |
        uv run indexers/${{ inputs.filename }}.py 1> output.txt 2>&1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Print Output.txt
      shell: bash
      run: |
        cat output.txt

    - name: Handle Error
      if: ${{ steps.parser.outcome == 'failure' }}
      uses: tsickert/discord-webhook@v6.0.0
      with:
        webhook-url: ${{ inputs.error_hook }}
        content: <@894312088762220605> Parser for ${{ inputs.filename }} failed!
        filename: output.txt