name: 'Run Parser'
description: ''
inputs:
  filename:
    required: true
  error_hook:
    required: true

runs:
  using: "composite"
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v5

    - name: Run Parser
      continue-on-error: true
      id: runner
      shell: bash
      run: |
        uv run _parsers/${{ inputs.filename }}.py &> $GITHUB_OUTPUT
    
    - name: Print Runner Outcome
      shell: bash
      run: echo ${{ steps.runner.outcome }}
    
    - name: Write output to file
      if: ${{ steps.runner.outcome == 'failure' }}
      uses: DamianReeves/write-file-action@master
      with:
        path: output.txt
        write-mode: overwrite
        contents: |
          ${{ steps.runner.output }}
    
    - name: Print Output.txt
      shell: bash
      run: |
        cat output.txt

    - name: Handle Error
      if: ${{ steps.runner.outcome == 'failure' }}
      uses: tsickert/discord-webhook@v6.0.0
      with:
        webhook-url: ${{ inputs.error_hook }}
        content: Parser for ${{ inputs.filename }} failed!
        filename: output.txt