jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - if: ${{ inputs.parser == 'all' || inputs.parser == 'autohotkey.com' }}
      name: index autohotkey.com
      uses: cibere/Rtfm-Indexes@run-parser-action
      with:
        error_hook: ${{ secrets.INDEX_ERROR_HOOK_URL }}
        filename: autohotkey.com
    - if: ${{ inputs.parser == 'all' || inputs.parser == 'developer.mozilla.org' }}
      name: index developer.mozilla.org
      uses: cibere/Rtfm-Indexes@run-parser-action
      with:
        error_hook: ${{ secrets.INDEX_ERROR_HOOK_URL }}
        filename: developer.mozilla.org
    - if: ${{ inputs.parser == 'all' || inputs.parser == 'docs.datasecurity.org' }}
      name: index docs.datasecurity.org
      uses: cibere/Rtfm-Indexes@run-parser-action
      with:
        error_hook: ${{ secrets.INDEX_ERROR_HOOK_URL }}
        filename: docs.datasecurity.org
    - if: ${{ inputs.parser == 'all' || inputs.parser == 'docs.qmk.fm' }}
      name: index docs.qmk.fm
      uses: cibere/Rtfm-Indexes@run-parser-action
      with:
        error_hook: ${{ secrets.INDEX_ERROR_HOOK_URL }}
        filename: docs.qmk.fm
    - if: ${{ inputs.parser == 'all' || inputs.parser == 'failure' }}
      name: index failure
      uses: cibere/Rtfm-Indexes@run-parser-action
      with:
        error_hook: ${{ secrets.INDEX_ERROR_HOOK_URL }}
        filename: failure
    - if: ${{ inputs.parser == 'all' || inputs.parser == 'flowlauncher' }}
      name: index flowlauncher
      uses: cibere/Rtfm-Indexes@run-parser-action
      with:
        error_hook: ${{ secrets.INDEX_ERROR_HOOK_URL }}
        filename: flowlauncher
    - if: ${{ inputs.parser == 'all' || inputs.parser == 'lua' }}
      name: index lua
      uses: cibere/Rtfm-Indexes@run-parser-action
      with:
        error_hook: ${{ secrets.INDEX_ERROR_HOOK_URL }}
        filename: lua
    - if: ${{ inputs.parser == 'all' || inputs.parser == 'mpv.io' }}
      name: index mpv.io
      uses: cibere/Rtfm-Indexes@run-parser-action
      with:
        error_hook: ${{ secrets.INDEX_ERROR_HOOK_URL }}
        filename: mpv.io
    - if: ${{ inputs.parser == 'all' || inputs.parser == 'ss64.com' }}
      name: index ss64.com
      uses: cibere/Rtfm-Indexes@run-parser-action
      with:
        error_hook: ${{ secrets.INDEX_ERROR_HOOK_URL }}
        filename: ss64.com
    - if: ${{ inputs.parser == 'all' || inputs.parser == 'voidtools.com' }}
      name: index voidtools.com
      uses: cibere/Rtfm-Indexes@run-parser-action
      with:
        error_hook: ${{ secrets.INDEX_ERROR_HOOK_URL }}
        filename: voidtools.com
    - continue-on-error: true
      name: Push Changes
      run: 'git fetch

        git pull

        git add indexes

        git -c user.name="github-actions[bot]" -c user.email="41898282+github-actions[bot]@users.noreply.github.com"
        commit --author="cibere <71997063+cibere@users.noreply.github.com>" -m "Auto
        Update Indexes"

        git push'
name: Auto Update
'on':
  schedule:
  - cron: 23 23 * * *
  workflow_dispatch:
    inputs:
      parser:
        default: all
        description: the parser to run
        options:
        - all
        - autohotkey.com
        - developer.mozilla.org
        - docs.datasecurity.org
        - docs.qmk.fm
        - failure
        - flowlauncher
        - lua
        - mpv.io
        - ss64.com
        - voidtools.com
        required: false
        type: choice
