name: Run Ruff
on:
    push:
    pull_request:
      types: [opened, reopened, synchronize, ready_for_review]

jobs:
  ruff-formatter:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: astral-sh/setup-uv@v5
    - run: uvx ruff format --check
  ruff-linter:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: astral-sh/setup-uv@v5
    - run: uvx ruff check