name: Tooling

on:
  push:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  tooling:
    runs-on: ubuntu-latest

    name: tooling
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run Tools
        uses: cibere/python-action@master
        with:
          pyright: 'true'
          ruff-linter: 'true'
          ruff-formatter: 'true'
          bandit: 'true'
          python-version: '3.13'
          requirements: '_ci/requirements.txt'