name: Update Script Dependencies
'on':
    workflow_dispatch:
    schedule:
      - cron: 23 23 * * *
permissions:
  contents: write
  pull-requests: write

jobs:
  update_deps:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.WORKFLOW_TOKEN }}
    - name: Install uv
      uses: astral-sh/setup-uv@v5
    - run: uv run .github/check_script_dependencies.py > output.txt
    - uses: peter-evans/create-pull-request@v7
      with:
        body-path: output.txt
        title: Upgrade Script Dependencies
        commit-message: Update script dependencies
        draft: always-true