name: Update Auto Script Dependencies
'on':
    workflow_dispatch:
    schedule:
      - cron: 23 23 * * *

jobs:
  update_deps:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.WORKFLOW_TOKEN }}
    - name: Install uv
      uses: astral-sh/setup-uv@v5
    - run: uv run .github/check_script_dependencies.py > output.txt
    - continue-on-error: true
      name: Push Changes
      run: |
        git add .
        git -c user.name="github-actions[bot]" -c user.email="41898282+github-actions[bot]@users.noreply.github.com" commit --author="cibere <71997063+cibere@users.noreply.github.com>" -m "Update script dependencies"
        git push -u update-script-deps-${{ github.run_id }}-${{ github.run_attempt }} --force
    - uses: peter-evans/create-pull-request@v7
      with:
        body-path: output.txt
        title: Upgrade Script Dependencies