name: Auto Update

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */3 * * *"


jobs:
  run-updater:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up CPython 3.13
        uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - name: Delete Old Indexes
        run: |
          rm -r -v -f indexes
          git add .
          git -c user.name="github-actions[bot]" -c user.email="41898282+github-actions[bot]@users.noreply.github.com" commit --author="cibere <71997063+cibere@users.noreply.github.com>" -m "Delete old indexes" --allow-empty

      - name: Install dependencies
        id: install-deps
        run: |
          python -m pip install -r _ci/requirements.txt

      - name: Create new indexes
        run: |
          python -m _ci
          git -c user.name="github-actions[bot]" -c user.email="41898282+github-actions[bot]@users.noreply.github.com" commit --author="cibere <71997063+cibere@users.noreply.github.com>" -m "create new indexes" --allow-empty

      - name: Push Changes
        continue-on-error: true
        run: |
          git reset --soft HEAD~2
          git -c user.name="github-actions[bot]" -c user.email="41898282+github-actions[bot]@users.noreply.github.com" commit --author="cibere <71997063+cibere@users.noreply.github.com>" -m "Auto Update Indexes"
          git push