name: Update Auto Update Workflow
'on':
  push:
  workflow_dispatch:

jobs:
  update_workflow:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.WORKFLOW_TOKEN }}
    - name: Install uv
      uses: astral-sh/setup-uv@v5
    - run: uv run .github/update_workflow_builder.py
    - continue-on-error: true
      name: Push Changes
      run: 'git fetch

        git pull

        git add .github/workflows/auto_update.yml

        git -c user.name="github-actions[bot]" -c user.email="41898282+github-actions[bot]@users.noreply.github.com"
        commit --author="cibere <71997063+cibere@users.noreply.github.com>" -m "Auto Update AutoUpdater Workflow"

        git push'
