name: Update Script Dependencies
'on':
    workflow_dispatch:
    schedule:
      - cron: 23 23 * * 0
permissions:
  contents: write
  pull-requests: write

jobs:
  update_deps:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: astral-sh/setup-uv@v5
    - run: uv run .github/check_script_dependencies.py > output.ignore
    - run: cat output.ignore
    - uses: peter-evans/create-pull-request@v7
      with:
        body-path: output.ignore
        title: Upgrade Script Dependencies
        commit-message: Update script dependencies
        draft: true
        branch: update-script-dependencies-${{ github.run_id }}.${{ github.run_attempt }}
        labels: dependencies